#version 150
#define FSH
#define BLOCK
#define VANILLA
#define TRANSLUCENT
#moj_import <template/template.glsl>
#moj_import <render/block_header.fsh.glsl>
#moj_import <render/block.fsh.glsl>
#moj_import <template/entry.glsl>