#version 150
#define VSH
#define BLOCK
#define VANILLA
#define TRANSLUCENT
#moj_import <template/bindings.glsl>
#moj_import <render/block_header.vsh.glsl>
#moj_import <render/block.vsh.glsl>
#moj_import <template/entry.glsl>