#version 150
#define FSH
#define BLOCK
#define VANILLA
#define SOLID
#moj_import <template/bindings.glsl>
#moj_import <render/block_header.fsh.glsl>
#moj_import <render/block.fsh.glsl>
#moj_import <template/entry.glsl>